# Generated by Django 5.0.6 on 2024-06-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('Comedia', 'Comédia'), ('Acao', 'Ação'), ('Drama', 'Drama')], max_length=7)),
                ('assentos', models.IntegerField()),
                ('elenco', models.CharField(max_length=200)),
                ('secoes', models.IntegerField()),
                ('data', models.DateField()),
                ('horarios', models.TimeField()),
                ('imagem', models.ImageField(upload_to='shows/')),
            ],
        ),
    ]
